name: Build macOS App and Release

on:
  push:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write      # 레포지토리 컨텐츠(코드) 읽기/쓰기
  packages: write      # 패키지 퍼블리싱 권한 (필요 시)

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install py2app pandas openpyxl XlsxWriter

      - name: Clean old build
        run: rm -rf build dist *.egg-info

      - name: Build app
        run: python3 setup.py py2app

      - name: Zip the app
        run: |
          cd dist
          zip -r NaverRankChecker.zip NaverRankChecker.app

      - name: Create GitHub Release and Upload
        uses: softprops/action-gh-release@v1
        with:
          name: NaverRankChecker
          tag_name: v1.0.${{ github.run_number }}
          files: dist/NaverRankChecker.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
