name: Build macOS App and Release

on:
  push:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'  # ✅ pip 캐시

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # 명시적으로 py2app 설치(안전)
          pip install py2app

      - name: Clean old build
        run: rm -rf build dist *.egg-info

      - name: Build app with py2app
        run: python setup.py py2app

      - name: Zip the app
        run: |
          cd dist
          zip -r NaverRankChecker.zip NaverRankChecker.app

      # ✅ 항상 CI 아티팩트로 업로드 (릴리스 여부와 무관)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: NaverRankChecker-macOS
          path: dist/NaverRankChecker.zip
          if-no-files-found: error
          retention-days: 7

      # ✅ push/workflow_dispatch에서 새 릴리스 생성
      - name: Create GitHub Release and Upload (auto-tag)
        if: ${{ github.event_name != 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          name: NaverRankChecker
          tag_name: v1.0.${{ github.run_number }}
          files: dist/NaverRankChecker.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ✅ release 이벤트로 실행된 경우, 해당 릴리스에 업로드만
      - name: Upload to existing Release (release event)
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.release.name }}
          tag_name: ${{ github.ref_name }}
          files: dist/NaverRankChecker.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
